package com.nfn8y.notesapp.common.model

import kotlinx.datetime.Clock
import kotlinx.datetime.Instant

data class Note(
    val id: Long?, // Changed to Long?, null for new notes before DB insertion
    val title: String,
    val content: String,
    val createdAt: Instant,
    val updatedAt: Instant
) {
    companion object {
        // Factory function for new notes (ID will be generated by the database)
        fun createNew(title: String, content: String): Note {
            val now = Clock.System.now()
            return Note(id = null, title = title, content = content, createdAt = now, updatedAt = now)
        }
    }
}