package com.nfn8y.notesapp.common.db

import app.cash.sqldelight.db.SqlDriver
import app.cash.sqldelight.driver.native.NativeSqliteDriver
import com.nfn8y.notesapp.db.AppDatabase // Generated by SQLDelight

actual class DatabaseDriverFactory {
    actual fun createDriver(): SqlDriver {
        return NativeSqliteDriver(AppDatabase.Schema, "notes.db")
    }
}